### ISSUE TITLE
Advertisement TTL

### ISSUE THREAD

**Issue by stephen** [agnat/node_mdns#105]
Is there a way to set the TTL for a given bonjour advertisement?

**Comment by victorgama** [comment]
I can confirm this problem is isolated to avahi.

I had a similar problem with some linux machines (Ubuntu Trusty) running avahi, and their advertisements did not disappear until the machine was restarted. The solution was to completely remove avahi and install mDNSResponder. Now everything behaves as expected (and I also got rid of those ugly warnings from avahi's compatibility layer).

A linux-compatible version of mDNSResponder can be found at https://github.com/gkaindl/Community-mdnsResponder, and there's also a nice installation script that automagically installs it: https://github.com/gkaindl/ubuntu-scripts/blob/master/apple-mdns-install.sh

@agnat You might consider including this information on README, so people can choose between avahi and mDNSResponder. I don't think it will be a problem to our open-source aficionado friends, since it has been open-sourced by Apple long ago. :sunglasses:
