### ISSUE TITLE
Wide Area discovery?

### ISSUE THREAD

**Issue by gtamas** [agnat/node_mdns#111]
Do you have any plans for adding this in the near future? As far as I know, Bonjour supports it and it would be a very useful feature.
According to your github page, this library supports LAN discovery only for now.

**Comment by agnat** [comment]
No work needed on my side. AFAIK it's all there. There is no special API to support WAN. However, I never explored that road since, to the best of my knowledge, nobody is actually using WAN bonjour. Also note that bonjour is a lot more than just service discovery. Think address negotiation, &c. I'm not sure the statement "Bonjour supports WAN" covers the service discovery part. What should it do anyway? Return a list of _all_ http servers?

So, no. I don't plan to do anything about WAN support in the near future. That said, patches, documentation and examples are always welcome.

**Comment by gtamas** [comment]
Ah OK I see, thx for the response.

I guess WAN service discovery  could be useful, it is actually used by some bonjour-enabled Apple (and other) apps at least. 
It could be especially useful in cases like mine.: There is a group of servers in a cloud, and there are clients supposed to connect to one of these servers. The number of servers will grow rapidly and the clients can be located anywhere in the world. 
I think bonjour service discovery could be a good way to let all the clients know about all registered servers without any locally stored config or adding "config servers". The former would result in a maintenance nightmare, the latter would introduce points of failure.
Of course there are other ways to do this, but using DNS servers to spread this data seems to be a better choice to me than a gossip protocol / p2p stuff.

Anyway thx again for the info. If there is no special API for WAN based service discovery, I should be able to make this work using current code base. Will look more into this.
