### ISSUE TITLE
Add SRV example to tutorial

### ISSUE THREAD

**Issue by appsforartists** [agnat/node_mdns#117]
Sadly, [.local names aren't accessible from iOS Safari](http://support.apple.com/en-us/TS3389) because it presumes anything ending in `.local` is registered with Bonjour.  For most developers, this is not true.

It would be really powerful if, as an HTTP server is being started from Node, it could also use `mdns` to broadcast its host as `mysite.local`.  Then you could test on any iOS device on the same subnet with 0 additional configuration.

**Comment by appsforartists** [comment]
Here's an example from my local network that works from iOS Safari:

```
_http._tcp                                      PTR     "Gramofon\032HTTPD-RPC"._http._tcp
"Gramofon\032HTTPD-RPC"._http._tcp              SRV     0 0 80 fonera.local. ; Replace with unicast FQDN of target host
"Gramofon\032HTTPD-RPC"._http._tcp              TXT     "Brenton's Gramofon"
```

**Comment by agnat** [comment]
Not sure I'm following. Lack of bonjour browsing is a (super longstanding) iOS Safari issue. 

> Here's an example [...]

Uh, example of what? Where are these three lines from? You are looking for an API to attach an additional SRV record, right?

**Comment by appsforartists** [comment]
I believe that was `dns-sd -Z`, showing the MDNS records other devices on my network are sending.  If I want to use `node-mdns` to send out a similar `SRV` record, how do I do it?

**Comment by appsforartists** [comment]
@agnat I was able to get it mostly working with Advertisement:

```javascript
mdns.createAdvertisement(
  mdns.tcp('http'), 
  8080, 
  {
    "host":       "bikeindex.local",
    "name":       "bikeindex",
    "domain":     "local",
  },
  function () {
    console.log(arguments);
  }
).start();
```

The problem is that the working MDNS hosts on my network have an `addresses` field, but I don't see a hook for that in `Advertisement.js`.

**Comment by appsforartists** [comment]
If I uncomment the `log` lines, I can see that `networkInterface` is working:

```
got IP 192.168.10.107 -> 4
interface index: 4
```

But this is not adding an Addresses field to the record.

**Comment by appsforartists** [comment]
Setting `interfaceIndex` to 0 does not fix this issue.

**Comment by agnat** [comment]
On a general note: This is a binding for Apple's mDNSResonder API. I can not manipulate the packets directly. I only expose what it's there...

I'd also recommend to read the documentation (Maybe even Apple's upstream docs). `networkInterface` only sets the interface to browse or advertise on. To the best of my knowledge it does not do anything on the wire level.

You mentioned an Addresses field in some record. Please be more specific on what you are looking at and what you expect to see. Maybe it is exactly that field, present in some of your records, that is causing the trouble with the tutorial.

I also still do not understand how all that mitigates the lack of bonjour browsing in iOS Safari. Could you give an example of what you actually enter in the URL field to reach your other devices?

All that said, mDNSResponder has an API to publish custom records. Unfortunately, it is currently not implemented in mdns (this add-on). Mostly because it is quite a chunk. However, if we manage to turn this ticket into an actual feature request I promise to look into it.

**Comment by appsforartists** [comment]
I haven't been able to compare using the `node-mdns` browser due to #116, so I've been using other tools to see what records are being broadcast on my network.  The `Addresses` field appears for all of them, but not for anything created with your library.

For instance, I can access my router at http://fonera.local/ in any browser (inc. iOS Safari).  [NetExplorer](https://itunes.apple.com/us/app/network-explorer/id394756555?mt=8) shows this record for it:

```
Name="Gramofon HTTPD-RPC"
Type=_http._tcp.
Domain=local.
Hostname=fonera.local.
Port=80

Addresses:
192.168.0.1


Brenton's Gramofon=
```

A similar record using `mdns.createAdvertisement` looks like this:

```
Name=bikeindex
Type=_http._tcp.
Domain=local.
Hostname=bikeindex.local.
Port=8080
```

Is there anything else I can share to help diagnose this?

**Comment by agnat** [comment]
Entering http://fonera.local is _not_ bonjour browsing as in service discovery. mdns will not help you with that. Name resolution and announcement is system business. Both seems to be broken on that Mac. 

Try installing [Bonjour Browser](http://www.macupdate.com/app/mac/13388/bonjour-browser) on the Mac and take a look at your router. Does it have addresses?

**Comment by appsforartists** [comment]
It does:

![screen shot 2015-01-19 at 3 17 03 pm](https://cloud.githubusercontent.com/assets/926648/5809521/43be0e1c-9fee-11e4-94ba-536ada903602.png)

My goal is to use mDNS to advertise that a web server is available at a particular address, because iOS is hardcoded to resolve `.local` addresses with mDNS.  I should be able to go to http://bikeindex.local:8080 and see my app running from any device on the subnet.

**Comment by agnat** [comment]
> It does:

hmk.

>  I should be able to go to http://bikeindex.local:8080 and see my app running from any device on the subnet.

You don't need service discovery for that. It works out of the box without mdns. The mac is reachable as http://hostname.local by any device that supports bonjour address resolution including iOS devices. If it doesn't work something is awfully wrong with the system or network. Very hard to debug from here...

Note that the broken address resolution is also the cause for #116. It discovers the services just fine but fails hard when trying to get an address.

**Comment by appsforartists** [comment]
I think you misunderstand.  I don't want to browse to "Brenton's MacBook.local", I want "bikeindex.local".  This detail is important, because there may be many services running on the same machine.  Just as my Mac by default can announce that "Brenton's MacBook.local" should resolve to "192.168.10.107", so too should these other services using mdns.

I think it's really close as is.  We just need to figure out why other services (like `fonera`) are broadcasting their IP addresses and node-mdns isn't.

**Comment by appsforartists** [comment]
Apparently I forgot to mention this earlier, but your [own example](http://agnat.github.io/node_mdns/user_guide.html#service_object_example) shows addresses being discovered from other services.  Do you know where those are coming from?

**Comment by agnat** [comment]
Hehe, and I think you misunderstand. http://something.local is always a _machine name_. Although mdns service discovery does provide multiple instances on a single host it does not fit your requirements since it is not available in iOS Safari.

On Mac OS the addresses are resolved using [DNSServiceGetAddrInfo](https://developer.apple.com/library/mac/documentation/Networking/Reference/DNSServiceDiscovery_CRef/index.html#//apple_ref/c/func/DNSServiceGetAddrInfo). But you  can not announce the address of a machine in user land. This is done by the operating system. Take a look at this [diagram](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/NetServices/Articles/domainnames.html#//apple_ref/doc/uid/TP40002460-TPXREF120). It shows the different layers.
