### ISSUE TITLE
Resolving multiple addresses for a hostname

### ISSUE THREAD

**Issue by XQANDAG** [agnat/node_mdns#137]
It seems that there is no way to resolve multiple IP addresses for a hostname? As far as I tested, there seems to be only a random one. (Which could be a link-locale address, for example)

**Comment by agnat** [comment]
> It seems that there is no way to resolve multiple IP addresses for a hostname?

Explicitly ask for both address families v4 and v6. [Here](http://agnat.github.io/node_mdns/user_guide.html#resolver_sequence) is an example. Also, read #108 since using bare numbers, like in the example is no longer supported on all platforms.

The real question is: Why? The addresses returned by the default behavior are perfectly valid...

**Comment by XQDEV** [comment]
Thanks for your response, agnat. I tried to customize the resolver sequence, but it doesn't seem to work on my platform. (Ubuntu 14.04) I'm requesting v4-Families since my network has multiple devices with multiple IPv4 addresses. (All of them have a link locale address and a user defined address) But the client, which implements the multicasting, doesn't necessarily has a link locale on its own, so the returned IP addresses aren't always that useful. (Even if the addresses are valid) I found a node module (multicast-dns), which works good on the hostname resolution, but the discovery functionality isn't nearly as good as the one of node_mdns. There are sometimes cases where you prefer one IP address over the other.

**Comment by agnat** [comment]
Hmk, ubuntu ... avahi. Avahi does not implement `DNSServiceGetAddrInfo`. In that case [this kludge](https://github.com/agnat/node_mdns/blob/master/lib/resolver_sequence_tasks.js#L144) is used. It uses OS name resolution (triggering an mdns lookup). Note that you can customize the whole resolution process to your needs.  Just write your own lookup task. It's in the manual ...

**Comment by XQDEV** [comment]
Thanks, I will figure out a way to handle this.
