### ISSUE TITLE
compat.c: read() failed: Interrupted system call

### ISSUE THREAD

**Issue by XQANDAG** [agnat/node_mdns#145]
This is a issue, which most likely is forced by my misuse of node_mdns, but maybe someone has a clue which leads to this behaviour I'm experiencing. (Because I'm highly interested in solving this somehow) 

I'm currently starting and stopping and re-creating the browser every three seconds. (It's an experiment, since restarting the discovery is somehow more reliable to finding the services which are really up.) No problem here, everything is fine. But after 1000~ intervals (edit: okay, this is totally random. It can even happen after a few cycles) , my node program becomes unresponsive. It doesn't crash, it does nothing. The program freezes and no debug output in the interval will appear anymore. Before this happens, I start to get  "compat.c: read() failed: Interrupted system call" on some either browser.stop() or browser.start() calls. 

I tried to get more information using nodes debugger, but if I try a "bt", the debugger is dead too. (No crash, but it hangs) If I kill and start the program, everything works fine again. Memory and processor usage are fine and aren't increasing, file descriptors aren't leaking due to the usage of browser.stop(). But what can lead to this behaviour? 

(Yes, I know, re-creating the browser isn't what the module is designed for. But it isn't even possible to restart a browser, since the underlying file descriptor becomes unavailable which leads to internal exceptions)

**Comment by agnat** [comment]
> [...] since restarting the discovery is somehow more reliable to finding the services which are really up

That's because it triggers a full discovery. It wakes every wifi radio on the local network and forces it to transmit things... draining the batteries. The timeouts are what they are for reasons. However, since it is an experiment and it isn't _my_ network here is what to try:

1. Run your application using a _debug version_ of node and enable _core dumps_ for the process
1. Wait until the process hangs and then _kill_ it
1. Inspect the resulting core using a C(++) debugger
1. Look at the stack trace and see where it hangs

> [...] re-creating the browser isn't what the module is designed for. But it isn't even possible to restart a browser [...]

In fact it isn't designed to _restart_ a browser (or ad for that matter). Recreating is the way to go.
