### ISSUE TITLE
DNSServiceRef is not initialized

### ISSUE THREAD

**Issue by cheshire137** [agnat/node_mdns#167]
I'm using mdns indirectly through https://github.com/GPMDP/electron-chromecast so maybe this issue belongs there. I'm getting this error in my Electron app just by calling `require('electron-chromecast')`:

<img width="796" alt="screen shot 2016-05-28 at 8 08 26 pm" src="https://cloud.githubusercontent.com/assets/82317/15630815/284209a6-2510-11e6-9948-126ae45eb180.png">

That is,

> Unexpected result while probing for avahi: TypeError: argument 4 must be a string (name)(…)

> node_modules/mdns/lib/avahi.js:28 Uncaught Error: DNSServiceRef is not initialized

I'm in OS X El Capitan and here's the output of `npm version`:

```
% npm version
{ huxleyfm: '0.0.1',
  npm: '3.9.3',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.2.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.47',
  zlib: '1.2.8' }
```

**Comment by cheshire137** [comment]
I was able to solve this by installing Xcode. I had the Xcode command line tools installed but installing regular Xcode fixed this.

**Comment by cheshire137** [comment]
Actually, after installing Xcode, restarting, opening Xcode and letting it install 'additional components', I'm getting this error again. Now I'm trying to call `const mdns = require('mdns');` directly and getting the error.

**Comment by nybblr** [comment]
Same error message; I had upgraded to Electron 1.2.0. Since Electron bundles its own version of Node, I rolled back to electron-prebuilt 1.1.3 and it works again for me.

**Comment by agnat** [comment]
Hi @cheshire137
Hi @nybblr 

thanks for the report. Mac OS is the "home-platform" of this add-on and so this certainly raises an eyebrow. Unfortunately I'm unable to reproduce this. The add-on works fine with vanilla node from v0.8 to v6.0.

Packages that ship their own version of node (electron, atom, node webkit, &c.) have a track record of getting it wrong every now and then. They also have their own set of install-time pitfalls... specially with native add-ons.

Since I don't know electron I'm currently a bit reluctant to dig in... unless there is evidence that the issue is really with mdns...

@cheshire137, one thing strikes me as odd: If installing Xcode (components) affects things, there has to be an earlier error... the thing you posted is probably just a follow-up. But then again: I don't know electron or electron-chromecast. So I'm not much help here... 

Sorry about that :-/

**Comment by cheshire137** [comment]
@nybblr, thanks! When I use `"electron-prebuilt": "1.2.0"` with mdns, I get the "DNSServiceRef is not initialized" error. When I switched to `"electron-prebuilt": "1.1.3"`, the error went away. I'll file an issue over on `electron-prebuilt` about this.

@agnat, re: Xcode fixing it then not really fixing it, I'm not sure what I did there. I may well have gotten mixed up and commented out the `require('electron-chromecast')` line when I thought I got it working after the Xcode install.
