### ISSUE TITLE
Issue installing Homebridge on Mac OS 10.12

### ISSUE THREAD

**Issue by pvwowern** [agnat/node_mdns#206]
Hi, I'm unable to install Homebridge on OS X 10.12 (Sierra) with latest xCode 9.2 and latest Node.js package 9.3.0. 
I have tried to install with both -
sudo npm -g install homebridge
&
sudo npm -g install homebridge --unsafe-perm

But I only get the below errors.

Anyone who can help me ?

Server:Downloads Patrik$ sudo npm -g install homebridge --unsafe-perm
Password:
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> mdns@2.3.4 install /usr/local/lib/node_modules/homebridge/node_modules/mdns
> node-gyp rebuild

make: *** No rule to make target `../../../../../../../../Users/Patrik', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/mdns
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by agnat** [comment]
Well, it works for me.

Not sure how you got there but it looks like there is stale makefile around. Remove the homebrew installation folder after failed attempts. In your case that should be `/usr/local/lib/node_modules/homebridge`. At the very least remove `/usr/local/lib/node_modules/homebridge/node_modules/mdns/build/` to get a fresh makefile.

Then try again...

From experience I know these things usually boil down to unexpected but correct behaviour when fiddling with  `sudo npm -g`. I'm going to close this, since it is not a bug in mdns.

**Comment by pvwowern** [comment]
I found the problem. My userprofile & folders was named "Patrik 1" and the " 1" caused the problem. With a new user without any spaces i was able install Home Bridge successfully.

So i think it´s a bug :)

**Comment by agnat** [comment]
Ok, but it's not in mdns. :)
